name: Pulumi
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - 'app/**'
jobs:
  preview:
    name: App Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && pulumi config set gcp:zone us-west1-a && pulumi config set gcp:project pulumi-development
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: app
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && pulumi preview && pulumi preview --diff
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1
          PULUMI_CI: pr
          PULUMI_ROOT: app
