name: Pulumi
on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
jobs:
  up:
    name: App Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && pulumi config set gcp:zone us-west1-a && pulumi config set gcp:project pulumi-development && pulumi config set devClusterStackRef metral/gke-cicd/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: app
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && $GITHUB_WORKSPACE/scripts/pull_down_dev_creds.sh && pulumi up
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          PULUMI_CI: up
          PULUMI_ROOT: app
