name: Pulumi
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - 'app/**'
jobs:
  preview:
    name: App Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: stack init ${{ github.sha }} && pulumi config set gcp:zone us-west1-a && pulumi config set gcp:project pulumi-development && pulumi config set devClusterStackRef metral/gke-cicd/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: app
      - uses: docker://pulumi/actions
        with:
          args: gsutil cp gs://${{ github.sha }}-sa-secret/key.json /tmp/key.json && gcloud auth activate-service-account --key-file /tmp/key.json && gcloud auth configure-docker
        env:
          PULUMI_CI: pr
          PULUMI_ROOT: app
      - uses: docker://pulumi/actions
        with:
          args: stack select -s {{ github.sha }} && pulumi preview && pulumi preview --diff
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1
          PULUMI_CI: pr
          PULUMI_ROOT: app
