name: Pulumi
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  up:
    name: Infra Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && pulumi config set gcp:zone us-west1-a && pulumi config set gcp:project pulumi-development && pulumi up
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: infra
