name: Pulumi
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - 'infra/**'
jobs:
  preview:
    name: Infra Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && pulumi config set gcp:zone us-west1-a && pulumi config set gcp:project pulumi-development
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: infra
      - uses: docker://pulumi/actions
        with:
          args: stack select -s dev && pulumi preview && pulumi preview --diff
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1
          PULUMI_CI: pr
          PULUMI_ROOT: infra
  test-cluster:
    name: Test Cluster
    needs: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: stack init ${{ github.sha }} && pulumi config set gcp:zone us-west1-a && pulumi config set gcp:project pulumi-development
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: infra
      - uses: docker://pulumi/actions
        with:
          args: stack select -s ${{ github.sha }} && pulumi up
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1
          PULUMI_CI: pr
          PULUMI_ROOT: infra
